### ISSUE TITLE
Kodi youtube notification: UNKNOWN

### ISSUE THREAD

**Issue by ghost** [allejok96/send-to-kodi#3]
I love the idea of this script! However, when I run it I see Kodi respond with a notification saying "unknown".
In terminal I get this response: {"id":1,"jsonrpc":"2.0","result":"OK"}
Used a normal youtube link, running mac Catalina.

**Comment by allejok96** [comment]
Funny, I just tried it out and it worked fine.

Does the notification say just "unknown"? Can you include any log output? What version of Kodi are you on?
