### ISSUE TITLE
MPEG-DASH support

### ISSUE THREAD

**Issue by ostanislaw** [allejok96/send-to-kodi#4]
Hello,

First I'd like to say it's very nice and powerfull script, yet simple and short.
Have you considered sending separate video and audio stream? Is it even possible with json-rpc kodi API?

Currently if I use the script it sends only 320p combined stream which is really poor. However with default action youtube-dl selects 720p but then these are separate video&audio streams.
Current youtube-dl usage by script:
```sh
youtube-dl -gf best 'https://www.facebook.com/watch/live/?v=190790559367200&ref=watch_permalink'
https://scontent.fwaw5-1.fna.fbcdn.net/v/t66.36281-6/10000000_907241116478824_1982327047256291720_n.mp4?_nc_cat=111&ccb=2&_nc_sid=985c63&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9zZCJ9&_nc_ohc=PTfIAsDM1AQAX-ltN9e&_nc_ht=scontent.fwaw5-1.fna&oh=50047fc087406a04a5171c254a61acb7&oe=5FF26A0A
```
Best quality 720p but 2 separate streams
```sh
youtube-dl -g 'https://www.facebook.com/watch/live/?v=190790559367200&ref=watch_permalink'
https://video.fwaw5-1.fna.fbcdn.net/v/t58.24163-29/10000000_374104710550142_4622832835349334323_n.mp4?_nc_cat=108&ccb=2&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfbGl2ZV9oZDFfdW1hX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=WP8B6o5LAe8AX_82cWM&_nc_ht=video.fwaw5-1.fna&oh=b2fdcfe3830940c0095d39992e5ddd4e&oe=5FCF5E6E
https://video.fwaw5-1.fna.fbcdn.net/v/t58.24163-29/10000000_803469820218481_3195184083453920485_n.mp4?_nc_cat=104&ccb=2&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfbGl2ZV9tZF91bWFfZnJhZ18yX2F1ZGlvIn0=&_nc_ohc=fISeck7tShoAX_xZei2&_nc_ht=video.fwaw5-1.fna&oh=af7fe1ac18f037f50eb531792ca1022b&oe=5FCFB9CF
```

**Comment by allejok96** [comment]
### The short answer: probably not at the moment

I've been reading and googling and reading, and I don't quite understand what I've read, but just for reference...

- There is a way of having external audio to *locally* stored files, by giving them similar names. (Does not work with STRM files, I've tried)
https://forum.kodi.tv/showthread.php?tid=221881

* The youtube addon has been (and still is from time to time) suffering from the same issue as you mentioned, but it has mostly been resolved by using *Mpeg DASH* (see top comments in link).
https://github.com/jdf76/plugin.video.youtube/issues/440

* DASH requires *InputStream.Adaptive* to be installed. InputStream.Adaptive is activated when a video has the property inputstream.adaptive.manifest_type. The property get set by an addon when it creates a list of playable videos.
https://github.com/peak3d/inputstream.adaptive

* It is possible to set those properties inside a *STRM file* tho.
https://forum.kodi.tv/showthread.php?tid=346141

* Seems like it's *not* possible to send them over a JSON-RPC request :(
https://github.com/peak3d/inputstream.adaptive/issues/227

* Just read them...? I don't know what I'm looking at.
https://kodi.wiki/view/JSON-RPC_API/v12#Item.CustomProperties

**Comment by ostanislaw** [comment]
Thank you for the research. I've quickly read all these links and I have no idea too if it's possible. For me the "workaround" is to just ssh to kodi box (osmc@rpi3), youtube-dl the video and then play it by kodi GUI. Probably a step forward but still local at kodi might be a script that youtube-dl best quality(it would merge 2 files) followed by jsonrpc of downloaded file, simple. Anyway I usually get some youtube videos to play for children and your script is helpful with that.

OK, if it is really not supported by json-rpc, and there is no other remote possibility then it might be possible to ssh to kodi prepare strm file with both links from youtube-dl and play it somehow with InputStream.Adaptive. I don't feel like trying to do that ;)
I don't expect the feature to be supported by kodi in near future (1-5 years). It's not the rocket science but I feel kodi have other priorities.

**Comment by allejok96** [comment]
Good suggestions, well, hacks. I've got one too:

Instead of using ssh one could have a companion addon for Kodi that takes some path like addon://sendtokodi/play?url=some_url and starts mpeg dash playback (or perhaps even uses youtube-dl on the Kodi machine to lookup the address). Wouldn't be surprised if it already exists. Anyhow I have no intention to develop such an addon, as the point of this script is that it's very simple and requires nothing but standard stuff (and I have no idea how dash works).

Here's another suggestion:

This script should already be able to stream a local media file to Kodi using netcat. I don't know if this actually works, maybe you can test it out? Then one could let youtube-dl download the file, and then stream it to Kodi... It will take longer, but it works...

**Comment by ostanislaw** [comment]
I've tried once to play local video (downloaded from first mp4 link at https://www.learningcontainer.com/mp4-sample-video-files-download/). There was a typical success json-rpc confirmation but video doesn't start to play, no visual reaction at kodi.
We could close this issue anyway.

**Comment by allejok96** [comment]
Oh wow, what a mess. But I wanted to get that local file sharing going again (Kodi is evil)...
Good thing is it was easy adding DASH support after that. The new version can download stuff for you too.
